export const ACTIONS_BUILD = {
  // --- Keyboard-only actions (no default voice triggers; path router covers voice) ---
  playPause: { label: "Playback: Play or Pause" },
  previous: { label: "Playback: Previous or Restart", notify: "mediaPrevious", gates: ["previousItem"] as const },
  next: { label: "Playback: Next", notify: "mediaNext", gates: ["nextItem"] as const },
  timeSkipFwd: { label: "Time: Skip forward", notify: "fwd" },
  timeSkipBwd: { label: "Time: Skip backward", notify: "bwd" },
  timeStart: { label: "Time: Restart", logic: [{ path: "media.intent.currentTime", op: "set", value: 0 }] },
  timeEnd: { label: "Time: End" },
  volumeUp: { label: "Volume: Increase", notify: "volumeUp", gates: ["volume"] as const },
  volumeDown: { label: "Volume: Decrease", notify: "volumeDown", gates: ["volume"] as const },
  brightnessUp: { label: "Brightness: Increase", notify: "brightnessUp", gates: ["brightness"] as const },
  brightnessDown: { label: "Brightness: Decrease", notify: "brightnessDown", gates: ["brightness"] as const },
  playbackRateUp: { label: "Playback: Increase speed", notify: "playbackRateUp", gates: ["playbackRate"] as const },
  playbackRateDown: { label: "Playback: Decrease speed", notify: "playbackRateDown", gates: ["playbackRate"] as const },
  timeStepFwd: { label: "Frame: Next (while paused)" },
  timeStepBwd: { label: "Frame: Previous (while paused)" },
  captions: { label: "Captions: Show or Hide", notify: "captions", gates: ["textVisible"] as const },
  captionsFontSizeUp: { label: "Captions: Font size increase", gates: ["textVisible"] as const },
  captionsFontSizeDown: { label: "Captions: Font size decrease", gates: ["textVisible"] as const },
  captionsFontFamily: { label: "Captions: Rotate font family", gates: ["textVisible"] as const },
  captionsFontWeight: { label: "Captions: Rotate font weight", gates: ["textVisible"] as const },
  captionsFontVariant: { label: "Captions: Rotate font variant", gates: ["textVisible"] as const },
  captionsFontOpacity: { label: "Captions: Rotate font opacity", gates: ["textVisible"] as const },
  captionsBackgroundOpacity: { label: "Captions: Rotate background opacity", gates: ["textVisible"] as const },
  captionsWindowOpacity: { label: "Captions: Rotate window opacity", gates: ["textVisible"] as const },
  captionsCharacterEdgeStyle: { label: "Captions: Rotate character edge style", gates: ["textVisible"] as const },
  captionsTextAlignment: { label: "Captions: Rotate text alignment", gates: ["textVisible"] as const },
  objectFit: { label: "Rotate object fit", gates: ["objectFit"] as const },
  capture: { label: "Frame: Capture", notify: "capture", gates: ["frameCapture"] as const },
  cast: { label: "Toggle cast", notify: "cast", gates: ["cast"] as const },
  airplay: { label: "Toggle airplay", notify: "airplay", gates: ["airplay"] as const },
  settings: { label: "Toggle settings", zen: true },
  // --- Logic-expressible actions (logic[] + keyboard, no default voice triggers) ---
  mute: { label: "Volume: Mute or Unmute", notify: "volumeMuted", gates: ["muted"] as const },
  dark: { label: "Brightness: Dark or Light", notify: "brightnessDark", gates: ["dark"] as const },
  fullscreen: { label: "Modes: Toggle fullscreen", notify: "fullscreen", logic: [{ path: "media.intent.fullscreen", op: "toggle" }], gates: ["fullscreen"] as const },
  theater: { label: "Modes: Toggle theater", notify: "theater", logic: [{ path: "media.intent.theater", op: "toggle" }], gates: ["theater"] as const },
  pictureInPicture: { label: "Modes: Toggle picture in picture", notify: "pictureInPicture", logic: [{ path: "media.intent.pictureInPicture", op: "toggle" }], gates: ["pictureInPicture"] as const },
  escape: { label: "Modes: Escape pop-up", zen: true },
  timeFormat: { label: "Time: Rotate format" },
  timeMode: { label: "Time: Switch mode" },
  // --- Compound (voice|time)-only actions (voice engine meta, path router can't reach these) ---
  reload: { label: "Reload player", zen: true },
  timeTravelUndo: { label: "Time travel: Undo", zen: true },
  timeTravelRedo: { label: "Time travel: Redo", zen: true },
  voiceQuit: { label: "Voice: Quit", zen: true, logic: [{ path: "settings.voice.active", op: "set", value: false }] },
  voiceMute: { label: "Voice: Mute", zen: true, logic: [{ path: "settings.voice.muted", op: "set", value: true }] },
  voiceSleep: { label: "Voice: Sleep", zen: true },
  voiceSubmit: { label: "Voice: Submit", zen: true, gates: ["voiceSubmit"] as const },
  voiceCtxFirst: { label: "Voice: Go to root", zen: true, gates: ["voiceItems"] as const },
  voiceCtxPrevious: { label: "Voice: Go back", zen: true, gates: ["previousVoiceItem"] as const },
  voiceCtxNext: { label: "Voice: Go forward", zen: true, gates: ["nextVoiceItem"] as const },
  voiceCtxLast: { label: "Voice: Go to leaf", zen: true, gates: ["voiceItems"] as const },
  voiceCtxReset: { label: "Voice: Reset context", zen: true, gates: ["voiceItems"] as const },
  voiceToggleOn: { label: "Voice: Turn on", zen: true },
  voiceToggleOff: { label: "Voice: Turn off", zen: true },
} as const;
