import { Action } from "@defs/action";

export const ACTIONS_BUILD = {
  // --- Keyboard-only actions (no default voice triggers; path router covers voice) ---
  playPause: { label: "Playback: Play or Pause" },
  previous: { label: "Playback: Previous or Restart", notify: "mediaPrevious", gates: ["previousItem"] },
  next: { label: "Playback: Next", notify: "mediaNext", gates: ["nextItem"] },
  timeSkipFwd: { label: "Time: Skip forward", notify: "fwd" },
  timeSkipBwd: { label: "Time: Skip backward", notify: "bwd" },
  timeStart: { label: "Time: Restart", logic: [{ path: "media.intent.currentTime", op: "set", value: 0 }] },
  timeEnd: { label: "Time: End" },
  timePreviousChapter: { label: "Time: Previous chapter", notify: "chapter" },
  timeNextChapter: { label: "Time: Next chapter", notify: "chapter" },
  volumeUp: { label: "Volume: Increase", notify: "volumeUp", gates: ["volume"] },
  volumeDown: { label: "Volume: Decrease", notify: "volumeDown", gates: ["volume"] },
  brightnessUp: { label: "Brightness: Increase", notify: "brightnessUp", gates: ["brightness"] },
  brightnessDown: { label: "Brightness: Decrease", notify: "brightnessDown", gates: ["brightness"] },
  playbackRateUp: { label: "Playback: Increase speed", notify: "playbackRateUp", gates: ["playbackRate"] },
  playbackRateDown: { label: "Playback: Decrease speed", notify: "playbackRateDown", gates: ["playbackRate"] },
  timeStepFwd: { label: "Frame: Next (while paused)" },
  timeStepBwd: { label: "Frame: Previous (while paused)" },
  captions: { label: "Captions: Show or Hide", notify: "captions", gates: ["textVisible"] },
  captionsFontSizeUp: { label: "Captions: Font size increase", gates: ["textVisible"] },
  captionsFontSizeDown: { label: "Captions: Font size decrease", gates: ["textVisible"] },
  captionsFontFamily: { label: "Captions: Rotate font family", gates: ["textVisible"] },
  captionsFontWeight: { label: "Captions: Rotate font weight", gates: ["textVisible"] },
  captionsFontVariant: { label: "Captions: Rotate font variant", gates: ["textVisible"] },
  captionsFontOpacity: { label: "Captions: Rotate font opacity", gates: ["textVisible"] },
  captionsBackgroundOpacity: { label: "Captions: Rotate background opacity", gates: ["textVisible"] },
  captionsWindowOpacity: { label: "Captions: Rotate window opacity", gates: ["textVisible"] },
  captionsCharacterEdgeStyle: { label: "Captions: Rotate character edge style", gates: ["textVisible"] },
  captionsTextAlignment: { label: "Captions: Rotate text alignment", gates: ["textVisible"] },
  objectFit: { label: "Rotate object fit", gates: ["objectFit"] },
  capture: { label: "Frame: Capture", notify: "capture", gates: ["frameCapture"] },
  settings: { label: "Toggle settings", zen: true },
  // --- Logic-expressible actions (logic[] + keyboard, no default voice triggers) ---
  mute: { label: "Volume: Mute or Unmute", notify: "volumeMuted", gates: ["muted"] },
  dark: { label: "Brightness: Dark or Light", notify: "brightnessDark", gates: ["dark"] },
  fullscreen: { label: "Modes: Toggle fullscreen", notify: "fullscreen", logic: [{ path: "media.intent.fullscreen", op: "toggle" }], gates: ["fullscreen"] },
  theater: { label: "Modes: Toggle theater", notify: "theater", logic: [{ path: "media.intent.theater", op: "toggle" }], gates: ["theater"] },
  pictureInPicture: { label: "Modes: Toggle picture in picture", notify: "pictureInPicture", logic: [{ path: "media.intent.pictureInPicture", op: "toggle" }], gates: ["pictureInPicture"] },
  cast: { label: "Modes: Toggle cast", notify: "cast", logic: [{ path: "media.intent.cast", op: "toggle" }], gates: ["cast"] },
  airplay: { label: "Modes: Toggle airplay", notify: "airplay", logic: [{ path: "media.intent.airplay", op: "toggle" }], notify: "airplay", gates: ["airplay"] },
  escape: { label: "Modes: Escape pop-up", zen: true },
  timeFormat: { label: "Time: Rotate format" },
  timeMode: { label: "Time: Switch mode" },
  // --- Compound (voice|time)-only actions (voice engine meta, path router can't reach these) ---
  reload: { label: "Reload player", zen: true },
  skipAd: { label: "Skip advertisement", zen: true, gates: ["adSkip"] },
  timeTravelUndo: { label: "Time travel: Undo", zen: true },
  timeTravelRedo: { label: "Time travel: Redo", zen: true },
  voiceWake: { label: "Voice: Wake up", zen: true, logic: [{ path: "settings.voice.active.value", op: "set", value: true }] },
  voiceQuit: { label: "Voice: Quit", zen: true, logic: [{ path: "settings.voice.active.value", op: "set", value: false }] },
  voiceMute: { label: "Voice: Mute or Unmute", zen: true, logic: [{ path: "settings.voice.muted", op: "toggle" }] },
  voiceSleep: { label: "Voice: Sleep", zen: true, logic: [{ path: "settings.voice.active.value", op: "set", value: "passive" }] },
  voiceSubmit: { label: "Voice: Submit", zen: true, gates: ["voiceSubmit"] },
  voiceCtxPrevious: { label: "Voice: Go back", zen: true, gates: ["previousVoiceItem"] },
  voiceCtxNext: { label: "Voice: Go forward", zen: true, gates: ["nextVoiceItem"] },
  voiceCtxClear: { label: "Voice: Clear context", zen: true, gates: ["voiceItems"] },
  voiceToggleOn: { label: "Voice: Turn on", zen: true },
  voiceToggleOff: { label: "Voice: Turn off", zen: true },
} as const satisfies Record<string, Omit<Action, "id">>;
