import type { Action } from "@defs/actions";


export const ACTIONS_BUILD: Record<string, Omit<Action, "id">> = {
  // --- Keyboard-only actions (no default voice triggers; path router covers voice) ---
  playPause: { label: "Play / Pause" },
  skipFwd: { label: "Skip Forward", notify: "fwd" },
  skipBwd: { label: "Skip Back", notify: "bwd" },
  volumeUp: { label: "Volume Up", notify: "volumeup" },
  volumeDown: { label: "Volume Down", notify: "volumedown" },
  brightnessUp: { label: "Brightness Up", notify: "brightnessup" },
  brightnessDown: { label: "Brightness Down", notify: "brightnessdown" },
  playbackRateUp: { label: "Playback Rate Up", notify: "playbackrateup" },
  playbackRateDown: { label: "Playback Rate Down", notify: "playbackratedown" },
  stepFwd: { label: "Step Forward", notify: "fwd" },
  stepBwd: { label: "Step Back", notify: "bwd" },
  prev: { label: "Previous", notify: "mediaprev" },
  next: { label: "Next", notify: "medianext" },
  captions: { label: "Captions", notify: "captions" },
  captionsFontSizeUp: { label: "Captions: Font Size Up" },
  captionsFontSizeDown: { label: "Captions: Font Size Down" },
  captionsFontFamily: { label: "Captions: Font Family" },
  captionsFontWeight: { label: "Captions: Font Weight" },
  captionsFontVariant: { label: "Captions: Font Variant" },
  captionsFontOpacity: { label: "Captions: Font Opacity" },
  captionsBackgroundOpacity: { label: "Captions: Background Opacity" },
  captionsWindowOpacity: { label: "Captions: Window Opacity" },
  captionsCharacterEdgeStyle: { label: "Captions: Character Edge" },
  captionsTextAlignment: { label: "Captions: Text Alignment" },
  objectFit: { label: "Object Fit" },
  capture: { label: "Capture Frame", notify: "capture" },
  cast: { label: "Cast", notify: "cast" },
  airplay: { label: "AirPlay", notify: "airplay" },
  dark: { label: "Dark Mode" },
  settings: { label: "Settings", zen: true },
  // --- Logic-expressible actions (logic[] + keyboard, no default voice triggers) ---
  mute: { label: "Mute", notify: "volumemuted" },
  fullscreen: { label: "Fullscreen", notify: "fullscreen", logic: [{ path: "media.intent.fullscreen", op: "toggle" }] },
  theater: { label: "Theater", notify: "theater", logic: [{ path: "media.intent.theater", op: "toggle" }] },
  pictureInPicture: { label: "Picture in Picture", notify: "pictureinpicture", logic: [{ path: "media.intent.pictureInPicture", op: "toggle" }] },
  timeFormat: { label: "Time Format" },
  timeMode: { label: "Time Mode" },
  // --- Compound (voice|time)-only actions (voice engine meta, path router can't reach these) ---
  timeTravelUndo: { label: "Time Travel: Undo", zen: true },
  timeTravelRedo: { label: "Time Travel: Redo", zen: true },
  voiceQuit: { label: "Voice: Quit", zen: true },
  voiceSleep: { label: "Voice: Sleep", zen: true },
  voiceSubmit: { label: "Voice: Submit", zen: true },
  voiceHistoryFirst: { label: "Voice: Go to Root", zen: true },
  voiceHistoryPrev: { label: "Voice: Go Back", zen: true },
  voiceHistoryNext: { label: "Voice: Go Forward", zen: true },
  voiceHistoryLast: { label: "Voice: Go to Leaf", zen: true },
  voiceHistoryClear: { label: "Voice: Clear History", zen: true },
  voiceToggleOn: { label: "Voice: Toggle On", zen: true },
  voiceToggleOff: { label: "Voice: Toggle Off", zen: true },
  // --- Raw key internals, dispatched but never shown in the Actions menu ---
  " ": { private: true },
  escape: { private: true },
  arrowleft: { private: true },
  arrowright: { private: true },
  arrowup: { private: true },
  arrowdown: { private: true },
  home: { private: true },
  end: { private: true },
  playpause: { private: true },
  "0": { private: true },
  "1": { private: true },
  "2": { private: true },
  "3": { private: true },
  "4": { private: true },
  "5": { private: true },
  "6": { private: true },
  "7": { private: true },
  "8": { private: true },
  "9": { private: true },
};
